# Generated by Django 2.2.28 on 2023-03-17 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0002_personnel_alter_machine_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='secu',
        ),
        migrations.AddField(
            model_name='personnel',
            name='nom',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(13)]),
        ),
    ]
